server.port=8080

spring.datasource.url=jdbc:postgresql://ep-misty-dew-axongice.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_nPyKY6X4WEQi

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.notifications.denuncias-recipient=Christian.pinochet@yahoo.cl

app.storage.type=${STORAGE_TYPE:local}

app.storage.r2.account-id=${R2_ACCOUNT_ID:}
app.storage.r2.access-key-id=${R2_ACCESS_KEY_ID:}
app.storage.r2.secret-access-key=${R2_SECRET_ACCESS_KEY:}
app.storage.r2.bucket=${R2_BUCKET:}
app.storage.r2.endpoint=${R2_ENDPOINT:}