spring.application.name=canal-etico
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:5432}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.show-sql=true
spring.profiles.active=prod