spring.application.name=canal-etico
spring.security.user.name=admin
spring.security.user.password={noop}admin123
spring.security.user.roles=ADMIN

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
app.storage.type=${STORAGE_TYPE:local}
